spring:
  application:
    name: config

  cloud:
    config:
      server:
        git:
          uri: "${configrepo}"


server:
  port: 8888


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka