spring:
  application:
    name: mutualfund
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/mu_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8461

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka