logging:
  level:
    root: info

spring:
  application:
    name: portfolio
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/mu_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: hclmutualfundtest@gmail.com
    password: uihocswhcstqalmj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

remote: http://54.145.166.44
local: http://localhost

url: ${local}

authPort: 8005
wallletPort: 8460
mf_servicePort: 8461
wishlistPort: 8412
porfolitPort: 8081

authUrl: ${url}:${authPort}
wishlist: ${url}:${wishlistPort}
portfolio: ${url}:${porfolitPort}
wallet_service: ${url}:${wallletPort}
mf_service: ${url}:${mf_servicePort}
